# British Pound futures.
metadata:
  ticker: 6B
  contract_multiplier: 62500
contract_specs:
  tick_size: 0.0001
  tick_value: 6.25
risk:
  slippage_k: 0.0008
  vol_penalty: 0.003
  max_leverage: 2.5
  max_position_size: 40
